/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Pixel Art Palette
        'bg': '#0D0E15',
        'surface': '#1A1B26',
        'surface-dim': '#11121A',
        'text': '#E0E6F1',
        'text-dim': '#565F89',
        'accent-cyan': '#7EE0FF',
        'accent-magenta': '#FF7EDB',
        'accent-gold': '#FFD93D',
        'border-pixel': '#2A2B3D',
        'shadow-pixel': '#08090F',
        'shadow-deep': '#05060A',
        // Original app colors
        'void-black': '#0D0D14',
        'pixel-purple': '#6C5CE7',
        'neon-cyan': '#00E5FF',
        'warm-white': '#F0EDE4',
        'mid-gray': '#8A8598',
        'pixel-pink': '#FF6B9D',
        'gold': '#FFD93D',
        'dark-surface': '#1A1A2E',
        'pixel-green': '#6BCB77',
        // Shadcn
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        'pixel': ['"Press Start 2P"', 'monospace'],
        'label': ['VT323', 'monospace'],
        'mono-labels': ['"VT323"', 'monospace'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'code': ['"JetBrains Mono"', 'monospace'],
        'thai': ['Kanit', 'sans-serif'],
      },
      borderRadius: {
        'pixel': '0px',
        'pixel-soft': '4px',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        'pixel': '4px 4px 0px 0px #08090F',
        'pixel-sm': '2px 2px 0px 0px #08090F',
        'pixel-lg': '4px 4px 0px 0px #08090F, 8px 8px 0px 0px #05060A',
        'pixel-inset': 'inset 2px 2px 0px 0px #08090F',
        'pixel-focus': 'inset 2px 2px 0px 0px #08090F, 0px 0px 0px 2px #7EE0FF',
      },
      spacing: {
        'px-1': '4px',
        'px-2': '8px',
        'px-3': '16px',
        'px-4': '24px',
        'px-5': '32px',
        'px-6': '48px',
        'px-8': '64px',
        'px': '1px',
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '30': '7.5rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '48': '12rem',
        '56': '14rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
        '120': '30rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "twinkle": {
          "0%, 100%": { opacity: "0.2" },
          "50%": { opacity: "0.8" },
        },
        "float-drift": {
          "0%": { transform: "translate(0, 0) rotate(0deg)" },
          "25%": { transform: "translate(30px, -40px) rotate(5deg)" },
          "50%": { transform: "translate(-20px, -80px) rotate(-3deg)" },
          "75%": { transform: "translate(40px, -40px) rotate(2deg)" },
          "100%": { transform: "translate(0, 0) rotate(0deg)" },
        },
        "heartbeat": {
          "0%, 100%": { transform: "scale(1)" },
          "10%": { transform: "scale(1.15)" },
          "20%": { transform: "scale(1)" },
          "30%": { transform: "scale(1.15)" },
          "40%": { transform: "scale(1)" },
        },
        "blink-cursor": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "pulse-aura": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.6" },
          "50%": { transform: "scale(1.1)", opacity: "0.8" },
        },
        "grid-slide-up": {
          "0%": { transform: "rotateX(60deg) translateZ(-200px) translateY(100%)", opacity: "0" },
          "100%": { transform: "rotateX(60deg) translateZ(-200px) translateY(0)", opacity: "1" },
        },
        "block-reveal": {
          "0%": { clipPath: "inset(0 100% 0 0)" },
          "100%": { clipPath: "inset(0 0% 0 0)" },
        },
        "typewriter": {
          from: { width: "0" },
          to: { width: "100%" },
        },
        "pixel-float": {
          "0%": { transform: "translate(0, 0)", opacity: "1" },
          "25%": { transform: "translate(4px, -8px)" },
          "50%": { transform: "translate(-4px, -16px)", opacity: "0.8" },
          "75%": { transform: "translate(4px, -24px)" },
          "100%": { transform: "translate(0, -32px)", opacity: "0" },
        },
        "flicker": {
          "0%, 100%": { opacity: "0.97" },
          "50%": { opacity: "1" },
        },
        "entrance-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "entrance-scale": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "twinkle": "twinkle 3s ease-in-out infinite",
        "float-drift": "float-drift 20s linear infinite",
        "heartbeat": "heartbeat 1.2s ease-in-out infinite",
        "blink-cursor": "blink-cursor 1s step-end infinite",
        "pulse-aura": "pulse-aura 4s ease-in-out infinite",
        "grid-slide-up": "grid-slide-up 1s ease-out forwards",
        "block-reveal": "block-reveal 0.4s steps(8) forwards",
        "typewriter": "typewriter 1.5s steps(20) forwards",
        "pixel-float": "pixel-float 1s steps(8) forwards",
        "flicker": "flicker 0.15s steps(2) infinite",
        "entrance-up": "entrance-up 0.4s steps(6) forwards",
        "entrance-scale": "entrance-scale 0.3s steps(4) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
